"""add_playlist_tables

Revision ID: 00df541ca212
Revises: c3d4e5f6a1b2
Create Date: 2026-07-16 12:35:42.220278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00df541ca212'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(length=1024), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    with op.batch_alter_table('streaming_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streaming_tokens_id'), ['id'], unique=False)

    op.create_table('playlist_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('artist', sa.String(length=512), nullable=False),
    sa.Column('album', sa.String(length=512), nullable=True),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('spotify_track_id', sa.String(length=64), nullable=True),
    sa.Column('tidal_track_id', sa.String(length=64), nullable=True),
    sa.Column('cover_url', sa.String(length=2048), nullable=True),
    sa.Column('proposed_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_synced_spotify', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_synced_tidal', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_songs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_songs_isrc'), ['isrc'], unique=False)

    op.create_table('playlist_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['playlist_songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'user_id', name='_playlist_rating_uc')
    )
    with op.batch_alter_table('playlist_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_ratings_id'), ['id'], unique=False)

    op.create_table('playlist_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['playlist_songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist_sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_sync_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('gig_checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gig_checklist_items_gig'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gig_checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gig_checklist_items_gig'), ['gig_id'], unique=False)

    with op.batch_alter_table('playlist_sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_sync_logs_id'))

    op.drop_table('playlist_sync_logs')
    with op.batch_alter_table('playlist_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_ratings_id'))

    op.drop_table('playlist_ratings')
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_songs_isrc'))
        batch_op.drop_index(batch_op.f('ix_playlist_songs_id'))

    op.drop_table('playlist_songs')
    with op.batch_alter_table('streaming_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streaming_tokens_id'))

    op.drop_table('streaming_tokens')
    # ### end Alembic commands ###
