"""add_dance_styles_to_songs

Revision ID: 0f449d875a38
Revises: 0ba4c6c97dad
Create Date: 2026-07-02 08:33:52.226057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f449d875a38'
down_revision: Union[str, Sequence[str], None] = '0ba4c6c97dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dance_styles', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('dance_styles')

    # ### end Alembic commands ###
