"""add_status_column_to_users

Revision ID: 2d3e2798b7a5
Revises: b9cfdf551dac
Create Date: 2026-03-15 11:24:42.607409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3e2798b7a5'
down_revision: Union[str, Sequence[str], None] = 'b9cfdf551dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), server_default='active', nullable=False))

    # Alle bestehenden User explizit auf 'active' setzen
    op.execute("UPDATE users SET status = 'active' WHERE status IS NULL OR status = ''")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
