"""add_gig_schedule_items

Revision ID: 7f61e0947ca6
Revises: 2d3e2798b7a5
Create Date: 2026-04-16 09:03:39.139608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f61e0947ca6'
down_revision: Union[str, Sequence[str], None] = '2d3e2798b7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gig_schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gig_id', sa.Integer(), nullable=False),
    sa.Column('item_datetime', sa.DateTime(), nullable=False),
    sa.Column('was', sa.String(length=512), nullable=False),
    sa.Column('wer', sa.String(length=512), nullable=False),
    sa.Column('wo', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gig_id', 'item_datetime', name='_gig_schedule_uc')
    )
    with op.batch_alter_table('gig_schedule_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gig_schedule_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gig_schedule_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gig_schedule_items_id'))

    op.drop_table('gig_schedule_items')
    # ### end Alembic commands ###
