"""add_streaming_credentials_to_db

Revision ID: a7e284ac3114
Revises: 00df541ca212
Create Date: 2026-07-16 13:06:50.640019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e284ac3114'
down_revision: Union[str, Sequence[str], None] = '00df541ca212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('client_secret_enc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('playlist_id', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_tokens', schema=None) as batch_op:
        batch_op.drop_column('playlist_id')
        batch_op.drop_column('client_secret_enc')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
